services:
  minio:
    # networks:
    #   - test
    image: minio/minio
    entrypoint: sh
    command: >
      -c 'mkdir -p /data/test-bucket && minio server /data'
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: 'USERNAME'
      MINIO_ROOT_PASSWORD: 'PASSWORD'
      MINIO_ADDRESS: ':9000'
      MINIO_CONSOLE_ADDRESS: ':9001'
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - minio_data:/data
  server:
    # networks:
    #   - test
    build: .
    depends_on: 
      - minio
    ports:
      - 8100:8000
    volumes:
      - server_data:/data
    environment:
      - MINIO_HOST=http://minio:9000

volumes:
  minio_data:
  server_data:

# networks:
#   test:
#     driver: bridge