# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: authenticator.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'authenticator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import errors_pb2 as errors__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61uthenticator.proto\x12\rauthenticator\x1a\x0c\x65rrors.proto\"5\n\x0fRegisterRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"]\n\x10RegisterResponse\x12\x12\n\x05token\x18\x01 \x01(\tH\x00\x88\x01\x01\x12!\n\x05\x65rror\x18\x02 \x01(\x0b\x32\r.errors.ErrorH\x01\x88\x01\x01\x42\x08\n\x06_tokenB\x08\n\x06_error\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"Z\n\rLoginResponse\x12\x12\n\x05token\x18\x01 \x01(\tH\x00\x88\x01\x01\x12!\n\x05\x65rror\x18\x02 \x01(\x0b\x32\r.errors.ErrorH\x01\x88\x01\x01\x42\x08\n\x06_tokenB\x08\n\x06_error2\xa0\x01\n\rAuthenticator\x12K\n\x08Register\x12\x1e.authenticator.RegisterRequest\x1a\x1f.authenticator.RegisterResponse\x12\x42\n\x05Login\x12\x1b.authenticator.LoginRequest\x1a\x1c.authenticator.LoginResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'authenticator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=52
  _globals['_REGISTERREQUEST']._serialized_end=105
  _globals['_REGISTERRESPONSE']._serialized_start=107
  _globals['_REGISTERRESPONSE']._serialized_end=200
  _globals['_LOGINREQUEST']._serialized_start=202
  _globals['_LOGINREQUEST']._serialized_end=252
  _globals['_LOGINRESPONSE']._serialized_start=254
  _globals['_LOGINRESPONSE']._serialized_end=344
  _globals['_AUTHENTICATOR']._serialized_start=347
  _globals['_AUTHENTICATOR']._serialized_end=507
# @@protoc_insertion_point(module_scope)
