# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import model_trainer_pb2 as model__trainer__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in model_trainer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ModelTrainerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Train = channel.unary_unary(
                '/model_trainer.ModelTrainer/Train',
                request_serializer=model__trainer__pb2.TrainRequest.SerializeToString,
                response_deserializer=model__trainer__pb2.TrainResponse.FromString,
                _registered_method=True)
        self.ListAvailableModels = channel.unary_unary(
                '/model_trainer.ModelTrainer/ListAvailableModels',
                request_serializer=model__trainer__pb2.ListAvailableModelsRequest.SerializeToString,
                response_deserializer=model__trainer__pb2.ListAvailableModelsResponse.FromString,
                _registered_method=True)
        self.GetPrediction = channel.unary_unary(
                '/model_trainer.ModelTrainer/GetPrediction',
                request_serializer=model__trainer__pb2.GetPredictionRequest.SerializeToString,
                response_deserializer=model__trainer__pb2.GetPredictionResponse.FromString,
                _registered_method=True)


class ModelTrainerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Train(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAvailableModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPrediction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelTrainerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Train': grpc.unary_unary_rpc_method_handler(
                    servicer.Train,
                    request_deserializer=model__trainer__pb2.TrainRequest.FromString,
                    response_serializer=model__trainer__pb2.TrainResponse.SerializeToString,
            ),
            'ListAvailableModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAvailableModels,
                    request_deserializer=model__trainer__pb2.ListAvailableModelsRequest.FromString,
                    response_serializer=model__trainer__pb2.ListAvailableModelsResponse.SerializeToString,
            ),
            'GetPrediction': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPrediction,
                    request_deserializer=model__trainer__pb2.GetPredictionRequest.FromString,
                    response_serializer=model__trainer__pb2.GetPredictionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'model_trainer.ModelTrainer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('model_trainer.ModelTrainer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModelTrainer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Train(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model_trainer.ModelTrainer/Train',
            model__trainer__pb2.TrainRequest.SerializeToString,
            model__trainer__pb2.TrainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAvailableModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model_trainer.ModelTrainer/ListAvailableModels',
            model__trainer__pb2.ListAvailableModelsRequest.SerializeToString,
            model__trainer__pb2.ListAvailableModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPrediction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model_trainer.ModelTrainer/GetPrediction',
            model__trainer__pb2.GetPredictionRequest.SerializeToString,
            model__trainer__pb2.GetPredictionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
